# Generated by Django 2.2 on 2021-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=254, unique=True)),
                ('lat', models.CharField(blank=True, max_length=254)),
                ('long', models.CharField(blank=True, max_length=254)),
                ('county', models.CharField(blank=True, max_length=254)),
                ('district', models.CharField(blank=True, max_length=254)),
                ('ward', models.CharField(blank=True, max_length=254)),
                ('constituency', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
