# Generated by Django 2.2 on 2021-05-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcodemodel',
            name='lat',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='postcodemodel',
            name='long',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
